services:
  random-fit_app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
      args:
        - username=${CONTAINER_USERNAME}
        - exec_user_id=${CONTAINER_EXEC_USER_ID}
    container_name: random-fit_app
    image: random-fit_app
    restart: "unless-stopped"
    volumes:
      - .:/srv/random-fit:shared
      - /etc/localtime:/etc/localtime:ro
    user: ${CONTAINER_EXEC_USER_ID}:${CONTAINER_EXEC_USER_ID}
    ports:
      - ${RF_DEBUGGER_TEST_PORT}:${RF_DEBUGGER_TEST_PORT}
    env_file:
      - .env