kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: random-fit-fs
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: ${RF_K8S_SHARED_FOLDER}
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: random-fit-pvc
spec:
  storageClassName: random-fit-fs
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }