// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-GB")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Combination definitions:":                  12,
	"Create combination definition:":            5,
	"Creating plan definition:":                 14,
	"Delete combination definition:":            10,
	"Delete plan definition:":                   24,
	"Edit combination definition file:":         7,
	"Edit combination definition:":              8,
	"Edit definition file:":                     18,
	"Edit script:":                              9,
	"Editing plan definition:":                  22,
	"Error creating combination folder:":        2,
	"Error creating definition folder:":         0,
	"Error creating plan folder:":               1,
	"Error creating storage folder:":            3,
	"Error deleting plan definition:":           25,
	"Error editing script:":                     19,
	"Error getting script:":                     17,
	"Error:":                                    15,
	"Finished creating combination definition:": 6,
	"Finished creating plan definition:":        16,
	"Finished deleting combination definition:": 11,
	"Finished deleting plan definition:":        26,
	"Finished editing plan definition:":         23,
	"Name is required.":                         4,
	"No combination definition found.":          27,
	"No combination definitions found.":         13,
	"No plan definition found.":                 28,
	"No plan definitions found.":                21,
	"Plan Definitions:":                         20,
}

var en_USIndex = []uint32{ // 30 elements
	0x00000000, 0x00000022, 0x0000003e, 0x00000061,
	0x00000080, 0x00000092, 0x000000b1, 0x000000db,
	0x000000fd, 0x0000011a, 0x00000127, 0x00000146,
	0x00000170, 0x00000189, 0x000001ab, 0x000001c5,
	0x000001cc, 0x000001ef, 0x00000205, 0x0000021b,
	0x00000231, 0x00000243, 0x0000025e, 0x00000277,
	0x00000299, 0x000002b1, 0x000002d1, 0x000002f4,
	0x00000315, 0x0000032f,
} // Size: 144 bytes

const en_USData string = "" + // Size: 815 bytes
	"\x02Error creating definition folder:\x02Error creating plan folder:\x02" +
	"Error creating combination folder:\x02Error creating storage folder:\x02" +
	"Name is required.\x02Create combination definition:\x02Finished creating" +
	" combination definition:\x02Edit combination definition file:\x02Edit co" +
	"mbination definition:\x02Edit script:\x02Delete combination definition:" +
	"\x02Finished deleting combination definition:\x02Combination definitions" +
	":\x02No combination definitions found.\x02Creating plan definition:\x02E" +
	"rror:\x02Finished creating plan definition:\x02Error getting script:\x02" +
	"Edit definition file:\x02Error editing script:\x02Plan Definitions:\x02N" +
	"o plan definitions found.\x02Editing plan definition:\x02Finished editin" +
	"g plan definition:\x02Delete plan definition:\x02Error deleting plan def" +
	"inition:\x02Finished deleting plan definition:\x02No combination definit" +
	"ion found.\x02No plan definition found."

	// Total table size 959 bytes (0KiB); checksum: 11DCB47B
